In [3]:
import numpy as np

print (np)
print(np.__version__)

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>
1.19.5


In [5]:
a = np.arange(15).reshape(3, 5)
print(a)

print(type(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>


In [8]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)

2
(3, 5)
15
int32
4


In [9]:
list(a)
a.tolist()

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]

In [10]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [12]:
np.arange(1.0, 3.0, 0.5, dtype="float64")

array([1. , 1.5, 2. , 2.5])